### ISSUE TITLE
error  Expected 'this' to be used by class method 'hello'  class-methods-use-this

### ISSUE THREAD

**Issue by roman-tremmel** [SebastienBtr/vue-dashboard#37]
Pretty sure it is not really an issue, but as a beginner on vue, I have no idea how to bring data on the dashboard using e.g. ESLint. Many of the examples [here](https://class-component.vuejs.org/guide/class-component.html#data) throw the error mentioned in the topic. 

For example adding following lines to the Home.vue file 

    <template>
     <div>
      <h1 class="title">My patients charchteristics</h1>
      <button v-on:click="hello">Click</button>
     </div>
    </template>
   
    <script lang="ts">
    import Vue from 'vue';
    import Component from 'vue-class-component';

    @Component({})
    export default class Home extends Vue {
      // Declared as component method
       hello() {
        console.log('Hello World!');
      }
    }
    </script>

Failed to compile.

    ./src/views/Home.vue
    Module Error (from ./node_modules/eslint-loader/index.js):

    /Users/X/Documents/vue-super-dash-example/vue2-example/src/views/Home.vue
     15:8  error  Expected 'this' to be used by class method 'hello'  class-methods-use-this

    ✖ 1 problem (1 error, 0 warnings)

This also:

    // See Hooks section for details about `data` hook inside class.
      data() {
         return {
          // `hello` will be reactive as it is declared via `data` hook.
          hello: undefined
        }
      }

I know about https://eslint.org/docs/rules/class-methods-use-this, but how to get data using API for instance?
Can you provide some links or help?

**Comment by SebastienBtr** [comment]
Your issue is not related to vue-dashboard, consider using stackoverflow for personal coding issues. If you use vscode you can install the eslint package which will show you the errors before you run the app, in your case you need to either use `this` in your `hello` function or disbale the rule for this line.
