### ISSUE TITLE
Width for sidebar

### ISSUE THREAD

**Issue by melaniemp** [SebastienBtr/vue-dashboard#40]
Hi Sebastien.
Is there an easy way to set up the sidebar width ?
Thanks !

**Comment by SebastienBtr** [comment]
Hey @melaniemp, I'll look into it and get back to you asap :)

**Comment by SebastienBtr** [comment]
Hey @melaniemp, I added a `sidebarWidth` param in version `2.0.4` and updated the readme :)

**Comment by melaniemp** [comment]
Thank you Sebastien. That's perfect ;)
